schema_version: 1

context:
  version: "0.1.3"

package:
  name: files_collections
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/files-collections/files_collections-${{ version }}.tar.gz
  sha256: 6f508bc1b8cc90a6cf2e38da894151027799db3e7912fb035aa53aec5a43e369

build:
  noarch: python
  number: 0
  script:
  # Install the generated package in the conda environment
    - python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-scm
  run:
    - docstring_parser
    - fsspec
    - h5netcdf
    - jinja2
    - netCDF4
    - numpy
    - python >=${{ python_min }}
    - requests
    - typer
    - xarray

tests:
  # --- Import tests without optional packages installed
  - python:
      pip_check: true
      imports:
        - fcollections
        - fcollections.utilities
        - fcollections.time
        - fcollections.missions
        - fcollections.core
        - fcollections.implementations
        - fcollections.sad
      python_version:
        - ${{ python_min }}.*
  # --- Import tests with optional packages installed
  - script:
      - python -c "import fcollections.geometry; import fcollections.implementations"
    requirements:
      run:
        - numba
        - dask
        - pyinterp
        - shapely
        - geopandas

about:
  summary: "Files Collections — Select and open files in a collection"
  license: Apache-2.0
  homepage: https://github.com/robin-cls/fcollections
  repository: https://github.com/robin-cls/fcollections
  license_file: LICENCE

extra:
  recipe-maintainers:
    - robin-cls
